version: "3"

services:
  order12306:
    image: hellozjf/order12306:1.0.0
    restart: unless-stopped
    volumes:
      - /root/docker/order12306/logs:/logs
    ports:
      - 12307:8080
    environment:
      - TZ=Asia/Shanghai

